// <auto-generated />
using DESPortal.Infrastructure.DataAccess.DESPortal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DESPortal.Infrastructure.Migrations
{
    [DbContext(typeof(DESPortalDBContext))]
    partial class DESPortalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DESPortal.Core.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("DESPortal.Core.Models.PlantToUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlantId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantsToUsers");
                });

            modelBuilder.Entity("DESPortal.Core.Models.PlantToUser", b =>
                {
                    b.HasOne("DESPortal.Core.Models.Plant", "Plant")
                        .WithMany("Users")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
